homelab_secrets:
    proxmox_api_token_id: ENC[AES256_GCM,data:/fNbeU70BCFi0yBCHekduZIx6DDv9Q==,iv:aM4f1jgxhCsiTsdKMrJoC6/yBam1A42yF/bqMABkNcA=,tag:zahMrjwLdGmmrTacZBhtOQ==,type:str]
    proxmox_api_token_secret: ENC[AES256_GCM,data:cYxEW9+/cCDwF2MLnSvsGj7NsZvIHFEoLCUN6cMIRVBWWxcW,iv:8Z9oHIC8hHF7SxQtSKVKVnH09pqytqeNMRxeT99JOTQ=,tag:x+kNAMSEL9g70dAejF4ppQ==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:DE1+7/xNhNJMyoAj0PQ1A16LM4m4AdwTYevNLJv+jYk7Hj4wcFcKoA==,iv:l3/USlrIdQ/T5SWKOQ+piK7Ufa9TMrB0zDu6eD6Lx00=,tag:ekdbe4sVlt2ZyjIodiQ7qA==,type:str]
    cloudflare_account_id: ENC[AES256_GCM,data:9RrqXVI3FUC03EnffaQLn10XlhCjrPPq6bvqfg6oUzM=,iv:qfhawlBLwp0QMFr/zzrozzFjmwx6NJba1qzwjTcJbGM=,tag:o+X/L9V5mB9GIva0l8ZUMw==,type:str]
    cloudflare_zone_id: ENC[AES256_GCM,data:0+MGE1vD7wz337Gb5ozrGMKRt1tpEu8/CTB3z0Dydzs=,iv:dojxuEQvT7i0cKBFHlSXvOzfjkL7wnE8/0Hc3yLdZPQ=,tag:73ccglzZYu2mIjfqxy7/aQ==,type:str]
    cloudflare_access_allowed_emails:
        - ENC[AES256_GCM,data:u7EsobNX5a46hHM666q1UCZ0bmL0crz3uQ==,iv:+TqHYljVZXDDOB3R4+nYAkzqOHtZa+TVU7AjaTXLbUM=,tag:tI2Q+kUPfXTHUoXSObZFHA==,type:str]
    postgres_password: ENC[AES256_GCM,data:pJpd48W8qzYEkJ5TK1FOZRXvndjc5K5ul8DwDvRANrjx6PYKwDgeZ2i5xT8=,iv:7f6mufghUemNwPDOH4ZYkCS7RU1GQ9Xb9UTITfo0Rjw=,tag:wgDkqmxZFU2nU8prZg4qyA==,type:str]
    n8n_encryption_key: ENC[AES256_GCM,data:1qB/rVWtNeYd/ZdSJQ320+5TYiw15k9DmKXXB03W4ns1tKYWtvj9LKe9nQo=,iv:2bkAkYRmzFW4f4sozjhpZDVRy94MukzHyte5UlYYBqg=,tag:OUFNcFIjK19O/gvu9NdhLA==,type:str]
    mqtt_username: ENC[AES256_GCM,data:V+8WVKQInRZsECW5,iv:VBj8Uh40kiacANDvSTNjDlXt/anQwVi2wzXWEzzKQXg=,tag:bvy2OtHv3exvqMu0NbdrPA==,type:str]
    mqtt_password: ENC[AES256_GCM,data:hvT6ShjpJm82VueNl5Ym3aK0IZ4fQM8Ng48MauFzF58=,iv:5zC3DnSTKk5tVNVRQnWeDK2dAD+lQEv/mRuE2lu16Wc=,tag:MTua3dRZ7GE2Sl+4gOHhLA==,type:str]
    zigbee2mqtt_network_key: ENC[AES256_GCM,data:GxwqfeRGTXqZ1Pmc+IHlw3MYusTo0Nn7I6Maa8kuAWfVL4CeCE1/u6L8vGiIg39q+OLX1wesQ+k0AadN13Yt+FsFDvwF7Y94,iv:hXA/S1cIesug05Xrvteuf2j0tUo4qh/QKIn5s2hVIx0=,tag:/7JT+6xhHAysa1ftVucTTg==,type:str]
    packer_ssh_password: ENC[AES256_GCM,data:Ml5hLefApe4UsyQfLWqFvTfA5l0kefHeLVCZjwuS3eo=,iv:zvaO2H+FepOUBl3Jr9VhT/djHq4x7mnhGJkcnMYoY4I=,tag:Q8ZrgOc65JUFoXYoarLUgA==,type:str]
    cloudbeaver_admin_name: ENC[AES256_GCM,data:Sy+a+NGkswk25jDK/jCd94g=,iv:WG4NLU4paiLKnBG171QUjGl+YdAEOgiK0dE2CU6Im+8=,tag:hT3GibMEAQ3Kfkoa/LVa8A==,type:str]
    cloudbeaver_admin_password: ENC[AES256_GCM,data:TcdVd4MQcf6Acv0UoVHJH34Xl+jRxi8A3XDwITFFazQ=,iv:u4JLojpeE8UG5ZG8+yPVSB/kGRkpC6ShjN+neeEL2GE=,tag:L7E1NUPmPu2L7maRDvMi8w==,type:str]
    uptime_kuma_admin_name: ENC[AES256_GCM,data:2zGVfN4=,iv:VZeDykpBl+yxOunllGNG97VIwKaiJH73+3+UwMoLwY0=,tag:0EXaXbsH2YcMjkCYJYyQfg==,type:str]
    uptime_kuma_admin_password: ENC[AES256_GCM,data:bYK4JOs6kDhKF9DDebxvb9yX7p6JK+v2UlCwxfl0O1k=,iv:SuXaJqC5vbZ1sMV90somDwzb7VteV3YNHIJoKXKiyxc=,tag:nZJqBXXnFoSwgbHXmHIIrQ==,type:str]
sops:
    age:
        - recipient: age1l8q5yj33vlmv6ttvcxv0cn2n8fhs8vkm8uj4pmydswkgwd3fzclsc5n0rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UnNuOGgzMEhTMEJVRzQ5
            M2VJTVAwTExGbktkTVgrSVpYdGZ2bHhWaDBvCm9ZNmMzcFFKUWdldm5WSG15VDN1
            bzUvcVRpVng1cGEzbS9EU0EvQlAxTDQKLS0tIGV6OW5VditURllNeU4yVXExc2RR
            KzR2Q0hrVktnaUFHTEN5T1dzdjZzL2MKlIhQBL/C9RgLRY6HxJ8/yYY1AbdFFdgA
            LCP2zpt+y/SYNzz3SuCEl5RdNVEOrwgRd3lWnStD8WiOE7PyYOVRsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T12:48:57Z"
    mac: ENC[AES256_GCM,data:z0cPYbViYV/rH4zJlnxCNIbKjnJUX6o7ms+hbLJtf5nKcnZMleYxN6nqh8S3BUoeV7irBNZrwhDRwcmxxGF0wzPQ6aEhABPiia2k1pXbqwtaHB1NRbhAascKy4whc9xTiu2L/uYriJxxlPj3yw4ChfmKXARG67Gx6Alpde1DpO0=,iv:4jKXYGfIu81sc2tMH0QvkQcJhj+QPH1peRSZf9ws6kk=,tag:ZTT9SDQS3Myp6HmVaPq65g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
