homelab_secrets:
    proxmox_api_token_id: ENC[AES256_GCM,data:9xYhMRB5GL8WC/QxYog2IHtxHUc2kA==,iv:4hX22F1k8xY867q+9An+Jd9WMlyHjT4BsCDmJ751+zI=,tag:zRnmg2euK2KmezrXq9Pqlg==,type:str]
    proxmox_api_token_secret: ENC[AES256_GCM,data:dA/0KjlqXyTvw0D5MjFhna76gG+mx+qkatl/ZunZjANLnuBq,iv:dzbRtWEVl0MCaj/N6oKMao1LYCrXxrBQcArwpOSjvlY=,tag:9DLklKxAA5PiNWXp510M9A==,type:str]
    cloudflare_api_token: ENC[AES256_GCM,data:RCQyZiGDV7wGUPnzaBp5U+0NyPNQ73WDQDEo/6uPP87XYhud7dDaXw==,iv:rg7p/YpF46XhlJGqUY5YuWxxT1ON2On+sjWbDAbxEqQ=,tag:C9tJ3/lyXFHzl9VOQ79INg==,type:str]
    cloudflare_account_id: ENC[AES256_GCM,data:a6LswgUoZ/ACYgLcsdo1IKVORtn9UebqfkmI3eimVNA=,iv:Pg56guf1SFTOJnkV1KrM3kj65JlvmBLBlMwd2a3JHiE=,tag:h5uFDuudsaMVbFMkXPLqdQ==,type:str]
    cloudflare_zone_id: ENC[AES256_GCM,data:WGZBUH6YRNaIQZ8maHqScvnThO4Qc8niftkINt3P5uw=,iv:TlN02YByMrD7HBtGC8M52/Mi+62I7x06bLREs2fQgPA=,tag:Nki3aMn/Am7KLsY83qk8ww==,type:str]
    cloudflare_access_allowed_emails:
        - ENC[AES256_GCM,data:jxbWzPT6DIXQ6f8AL4A68BH+2sHtiFiz9g==,iv:b/S0omwZfz0CQiBVZLj1c2rb2+xXtODg9149c+hybHk=,tag:eQ1vTvYFOBJA/Vsk/ry+yQ==,type:str]
    postgres_password: ENC[AES256_GCM,data:5hq3gMyoqV7oSOSGrJOd+omKcDvQtlkqSJr1wViCKtI5/avupMjaT1C4p1Y=,iv:AMyw5z2hJd2/IPQm0GFpM9GIqnGlBd+QK4lojkKs7zA=,tag:HudxV0TZ4+z/4+xaX4+aFQ==,type:str]
    n8n_encryption_key: ENC[AES256_GCM,data:R3mptiLTBFY38ra+PqbTP6mJRXzAuh1JPNBVzEp6rgG6czyDT2a8qV5OjAE=,iv:iqicG6XGDiwKCV7EEgN8a70eyOQfNRQmhVymOyUNGYU=,tag:PYy4cc4LUz3+Y+H5UhDS7Q==,type:str]
    packer_ssh_password: ENC[AES256_GCM,data:CAfVta00kDZ4nuvH5tCv6T+/crCe3/dObwAijli23Bo=,iv:wIBGvIKEVjgsd3W/4s7v5r3OfrZgNd1/FHYzuW2Tgcg=,tag:izo3yFjFBOBefqMzYgDtCA==,type:str]
sops:
    age:
        - recipient: age1l8q5yj33vlmv6ttvcxv0cn2n8fhs8vkm8uj4pmydswkgwd3fzclsc5n0rz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM3ozcjd5MWdYNkFtSlpv
            MXR5RjFkblIwSFFJYVFmVjRYVDBrMVA0aFNnCktRbDNmeXdRNGplb3JpWTBHZXRM
            M2g1a0dUeWovelhNM3NLREN2YWNuWUUKLS0tIDdaVWlqandYTWdkV1BEYUllMXdk
            MnR2TDhEdE5neWo3aFYxM0p5RU5nSTQKhUPBcrcyG+8WvV92Ud4DTOV9wx5oWDBv
            GO7+6GfdVKep4Wz4CG8dn4fZ9dZNeKUXmhw6/MqigVT46LbkWluOXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:17:55Z"
    mac: ENC[AES256_GCM,data:LKFtIUSzilremnylNGnK7L4fmov6DqP9LGvsN/LK5/iahnVCL/+gtvL1ZvB+KXce0Nef0E2mYJ9FThQh+Oc29tnl0no0hrNN3Yc5ofXJB/6d607g9ME0Rq7XjNdfMrVhZD7AoWgW4NnYZPj3fdkOb4sqM4f4J0NP4JD7zkrMmiQ=,iv:DUgh5BSptWAPfrmXfXwkZR+EizPAuupjECBNmAQYPuw=,tag:gxGkYS7d7OfAVW0IW4+v7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
