apiVersion: v1
kind: Namespace
metadata:
  name: homepage
  labels:
    app: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  services.yaml: |
    - Homelab:
        - Home Assistant:
            icon: home-assistant.png
            href: https://home.homelab.local
            description: Smart Home Platform
        - n8n:
            icon: n8n.png
            href: https://n8n.homelab.local
            description: Workflow Automation
        - Nextcloud:
            icon: nextcloud.png
            href: https://nextcloud.homelab.local
            description: File Storage & Collaboration
        - Ollama:
            icon: ollama.png
            href: https://ollama.homelab.local
            description: Local LLM (ChatGPT-like)

    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: https://grafana.homelab.local
            description: Monitoring Dashboards
        - Prometheus:
            icon: prometheus.png
            href: https://prometheus.homelab.local
            description: Metrics
        - Uptime Kuma:
            icon: uptime-kuma.png
            href: https://uptime.homelab.local
            description: Uptime Monitoring

    - Admin:
        - ArgoCD:
            icon: argocd.png
            href: https://argocd.homelab.local
            description: GitOps
        - Proxmox:
            icon: proxmox.png
            href: https://192.168.1.100:8006
            description: Hypervisor

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "K3s Cluster"
    - resources:
        backend: kubernetes
        expanded: true
        cpu: true
        memory: true

  settings.yaml: |
    title: Homelab Dashboard
    theme: dark
    headerStyle: boxed
    hideVersion: true

  bookmarks.yaml: |
    - Documentation:
        - Kubernetes:
       - abbr: K8s
              href: https://kubernetes.io/docs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: config
              mountPath: /app/config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: homepage-config
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: homepage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dashboard.homelab.local
      secretName: homepage-tls
  rules:
    - host: dashboard.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 3000
