---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  BREWFILE: "{{ .ROOT_DIR }}/taskfiles/Workstation/Brewfile"

tasks:
  setup:
    desc: Set up workstation
    deps: [":ansible:install"]
    cmds:
      - task: brew

  brew:
    desc: Install workstation dependencies with Brew
    cmd: brew bundle --file {{ .BREWFILE }}
    preconditions:
      - msg: "Homebrew is not installed. Head to https://brew.sh to get up and running."
        sh: "command -v brew"
      - msg: "Missing Brewfile"
        sh: "test -f {{ .BREWFILE }}"
