services:
  kiosk:
    build: .
    container_name: kiosk
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./config/routine.json:/usr/share/nginx/html/config/routine.json:ro
      - ./config/major-events.json:/usr/share/nginx/html/config/major-events.json:ro
      - ./config/chinese.json:/usr/share/nginx/html/config/chinese.json:ro
