# Ansible Inventory - Generated by OpenTofu
# DO NOT EDIT MANUALLY - This file is auto-generated

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
    
  children:
    k3s_cluster:
      vars:
        k3s_version: v1.28.5+k3s1
        k3s_token: "${k3s_token}"
        metallb_ip_range: "${metallb_ip_range}"
        
      children:
        k3s_master:
          hosts:
            ${master_name}:
              ansible_host: ${master_ip}
              node_type: master
              
        k3s_worker:
          hosts:
%{ for worker in workers ~}
            ${worker.name}:
              ansible_host: ${worker.ansible_host}
              node_type: worker
%{ endfor ~}
              
