---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  init:
    desc: Initialize OpenTofu
    dir: opentofu
    cmds:
      - tofu init
    sources:
      - "*.tf"

  plan:
    desc: Plan OpenTofu changes
    dir: opentofu
    deps: [init]
    cmds:
      - tofu plan
    preconditions:
      - msg: "terraform.tfvars not found. Copy terraform.tfvars.example and configure it"
        sh: "test -f terraform.tfvars"

  apply:
    desc: Apply OpenTofu changes to create K8s cluster VMs
    dir: opentofu
    deps: [init]
    cmds:
      - tofu apply -auto-approve
    preconditions:
      - msg: "terraform.tfvars not found. Copy terraform.tfvars.example and configure it"
        sh: "test -f terraform.tfvars"

  destroy:
    desc: Destroy K8s cluster VMs
    dir: opentofu
    cmds:
      - tofu destroy -auto-approve
    preconditions:
      - msg: "Are you sure you want to destroy the cluster? This cannot be undone!"
        sh: "false"

  destroy-confirm:
    desc: Destroy K8s cluster VMs (with confirmation bypass)
    dir: opentofu
    cmds:
      - tofu destroy -auto-approve

  output:
    desc: Show OpenTofu outputs (VM IPs)
    dir: opentofu
    cmds:
      - tofu output

  show:
    desc: Show current OpenTofu state
    dir: opentofu
    cmds:
      - tofu show

  validate:
    desc: Validate OpenTofu configuration
    dir: opentofu
    cmds:
      - tofu validate

  fmt:
    desc: Format OpenTofu files
    dir: opentofu
    cmds:
      - tofu fmt

  refresh:
    desc: Refresh OpenTofu state
    dir: opentofu
    cmds:
      - tofu refresh
